apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: yournamespace
  labels:
    k8s-app: caddy
  annotations:
    cloud.google.com/neg: '{"ingress": false}'
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
spec:
  type: NodePort
  ports:
    - name: http-port
      port: 80
      targetPort: 80
      protocol: 'TCP'
    - name: https-port
      port: 443
      targetPort: 443
      protocol: 'TCP'
  selector:
    k8s-app: caddy
